etcd:
  hosts:
    etcd0:
      ansible_host: 192.168.180.159

control:
  hosts:
    control0:
      ansible_host: 192.168.180.161

load_balancer:
  hosts:
    nginx0:
      ansible_host: 192.168.180.166

base:
  children:
    etcd:
    control:
    