etcd:
  hosts:
    etcd0:
      ansible_host: 192.168.180.159
      etcd_hostname: etcd0
  vars:
    ansible_user: etcd
    ansible_password: etcd
    ansible_become_password: etcd

control:
  hosts:
    control0:
      ansible_host: 192.168.180.161
      etcd_hostname: control0
  vars:
    ansible_user: control
    ansible_password: control
    ansible_become_password: control

lb:
  hosts:
    nginx0:
      ansible_host: 192.168.180.165
  vars:
    ansible_user: lb
    ansible_password: lb
    ansible_become_password: lb

base:
  children:
    etcd:
    control:
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    ansible_become: true
    