base:
  hosts:
    etcd0:
      ansible_host: 192.168.180.155
  vars:
    ansible_user: test
    ansible_password: test
    ansible_become_password: test

etcd:
  hosts:
    etcd0:
      ansible_host: 192.168.180.155
      etcd_hostname: etcd0
  vars:
    ansible_user: test
    ansible_password: test
    ansible_become_password: test

cluster:
  children:
    base:
    etcd:
  vars:
    ansible_python_interpreter: /usr/bin/python3.12
    ansible_become: true
    