- name: get setup file
  copy:
    src: "{{ setup_file }}"
    dest: .

- name: grant permission file
  file:
    path: setup.sh
    mode: 0700

- name: setup base virtual machine
  shell: ./setup.sh base --k8s-version {{ k8s_version }} --cni-version {{ cni_version }} --runtime-container {{ runtime_container }}
