Vagrant.require_version ">= 2.4.1"

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.box = "k8s-node"
  config.vm.box_check_update = false
  config.vm.provision "shell", inline: <<-SHELL
    echo "Updating ..."
  SHELL
end
