Vagrant.require_version ">= 2.4.2"

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.hostname = "node-1"
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "vmware" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "Updating ..."
  SHELL
end
