- name: setup base machines
  hosts: base
  gather_facts: false
  roles:
    - common
  vars:
    setup_file: ../k8s_setup_tools/script/setup.sh
    runtime_container: unix:///var/run/containerd/containerd.sock
    cni_version: v1.6.0
    k8s_version: v1.31

- name: setup load balancer machines
  hosts: load_balancer
  gather_facts: false
  roles:
    - load_balancer
  vars:
    data_folder: ../data

- name: setup etcd machines
  hosts: etcd
  gather_facts: false
  roles:
    - etcd
  vars:
    data_folder: ../data

- name: setup control machines
  hosts: control
  gather_facts: false
  roles:
    - control
  vars:
    data_folder: ../data

